import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.jetbrains.kotlin.android)
}

def signingPropertiesFile = rootProject.file("keystore.properties")
def signingProperties = new Properties()
if (signingPropertiesFile.exists()) {
    signingPropertiesFile.withInputStream { signingProperties.load(it) }
}

android {
    namespace 'com.suixin.sx2libra'
    compileSdk 34

    defaultConfig {
        applicationId "com.suixin.sxRnHelper"
        minSdk 26
        targetSdk 34
        versionCode 100
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        if (signingPropertiesFile.exists()) {
            release {
                storeFile rootProject.file(signingProperties["storeFile"])
                storeType signingProperties["storeType"]
                keyAlias signingProperties["keyAlias"]
                storePassword signingProperties["storePassword"]
                keyPassword signingProperties["keyPassword"]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (signingPropertiesFile.exists()) {
                signingConfig signingConfigs.release
            }
        }
        debug {
            debuggable true
            minifyEnabled false
            if (signingPropertiesFile.exists()) {
                signingConfig signingConfigs.release
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    packaging {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.activity.ktx
    testImplementation libs.androidx.lifecycle.viewmodel.savedstate
    implementation libs.androidx.recyclerview
    implementation libs.material
    implementation libs.kotlinx.coroutines.android
    implementation libs.mmkv

    testImplementation libs.junit
    testImplementation libs.kotlinx.coroutines.test
    androidTestImplementation libs.androidx.junit
}
